Add click<8.1.0 to requirements (fixes installation)
kraken 3.0.9 requires click, and by default click==8.1.2 is installed
with Python 3.8 and 3.9.

With click>=8.1.0 `python manage.py check` fails with an error:

    [...]
      File "/home/stweil/src/gitlab/scripta/work/app/escriptorium/settings.py", line 18, in <module>
        from kraken.kraken import SEGMENTATION_DEFAULT_MODEL
      File "/home/stweil/src/gitlab/scripta/venv3.8/lib/python3.8/site-packages/kraken/kraken.py", line 310, in <module>
        @cli.resultcallback()
    AttributeError: 'Group' object has no attribute 'resultcallback'

It works fine with click<8.1.0.

Signed-off-by: Stefan Weil <sw@weilnetz.de>