Add missing alt attribute to image in HTML code
This fixes an error message from W3C validator:

    Error: An img element must have an alt attribute, except under certain conditions.

Signed-off-by: Stefan Weil <sw@weilnetz.de>